server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway:
            filter: TRACE

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chahirchalouati/microservices-configurations
          default-label: master
          force-pull: true
          refresh-rate: 5

