server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway:
            filter: INFO
---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chahirchalouati/gramify-ms-configurations.git
          default-label: main
          force-pull: true
          refresh-rate: 5
      profile: docker,prod

---
spring:
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/IdeaProjects/gramify-ms-configurations
      profile: dev