version: '3.3'
services:
  configuration-service:
    build:
      context: ../../configuration-service/
      dockerfile: DockerFile
      args:
        USER_NAME: chahirchaloauti
        PASSWORD: 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
        ID: github
    ports:
      - '8888:8888'
    networks:
      - l_net

  audit-service:
    build:
      context: ../../audit-service/
      dockerfile: DockerFile
      args:
        USER_NAME: chahirchaloauti
        PASSWORD: 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
        ID: github
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.cloud.config.uri": "http://configuration-service:8888",
        "spring.config.activate.on-profile":"docker"
      }'
    depends_on:
      - mongo
      - configuration-service
      - authentication-service
    ports:
      - '7003:7003'
    networks:
      - l_net

  authentication-service:
    build:
      context: ../../authentication-service/
      dockerfile: DockerFile
      args:
        USER_NAME: chahirchaloauti
        PASSWORD: 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
        ID: github
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.cloud.config.uri": "http://configuration-service:8888",
        "spring.config.activate.on-profile":"docker"
      }'
    depends_on:
      - configuration-service
    ports:
      - '9000:9000'
    networks:
      - l_net

  post-service:
    build:
      context: ../../post-service/
      dockerfile: DockerFile
      args:
        USER_NAME: chahirchaloauti
        PASSWORD: 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
        ID: github
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.cloud.config.uri": "http://configuration-service:8888",
        "spring.config.activate.on-profile":"docker"
      }'
    depends_on:
      - mysql-db
      - configuration-service
      - authentication-service
    ports:
      - '7005:7005'
    networks:
      - l_net

  proxy-service:
    build:
      context: ../../proxy-service/
      dockerfile: DockerFile
      args:
        USER_NAME: chahirchaloauti
        PASSWORD: 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
        ID: github
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.cloud.config.uri": "http://configuration-service:8888",
        "spring.config.activate.on-profile":"docker",
        "spring.config.activate.on-profile":"docker"
      }'
    depends_on:
      - configuration-service
      - authentication-service
    ports:
      - '9999:9999'
    networks:
      - l_net
  notification-service:
    build:
      context: ../../notification-service/
      dockerfile: DockerFile
      args:
        USER_NAME: chahirchaloauti
        PASSWORD: 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
        ID: github
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.cloud.config.uri": "http://configuration-service:8888",
        "spring.config.activate.on-profile":"docker"
      }'
    depends_on:
      - configuration-service
      - authentication-service
    ports:
      - '9999:9999'
    networks:
      - l_net
  storage-service:
    build:
      context: ../../storage-service/
      dockerfile: DockerFile
      args:
        USER_NAME: chahirchaloauti
        PASSWORD: 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
        ID: github
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.cloud.config.uri": "http://configuration-service:8888",
        "spring.config.activate.on-profile":"docker"
      }'
    depends_on:
      - configuration-service
      - authentication-service
    ports:
      - '7010:7010'
    networks:
      - l_net
  social-service:
    build:
      context: ../../clients/social/
      dockerfile: DockerFile
    container_name: client
    ports:
      - "4200:4200"
      - '49153:49153'
    volumes:
      - .:/app
      - nodemodules:/app/node_modules

