version: '3.3'
services:
  jmeter:
    image: justb4/jmeter
    ports:
      - "1099:1099"
    volumes:
      - "/host/directory:/jmeter"
    environment:
      - DISPLAY=:0
  minio:
    image: minio/minio
    container_name: minio
    command: server --console-address ":9001" /export
    ports:
      - "47017:9000"
      - "47018:9001"
    environment:
      MINIO_ROOT_USER: myaccesskey
      MINIO_ROOT_PASSWORD: mysecretkey
      MINIO_BUCKET: storage
    volumes:
      - minio:/export
    networks:
      - l_net
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 myaccesskey myaccesskey;
      /usr/bin/mc mb myminio/storage;
      /usr/bin/mc policy set private myminio/somebucketname;
      exit 0;
      "
  mysql-db:
    image: mysql:8
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - mysql-db:/var/lib/mysql
    networks:
      - l_net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbit-conf:/var/lib/rabbitmq/
      - rabbit-log:/var/log/rabbitmq
    networks:
      - l_net
  mongo:
    image: mongo:6.0.2
    container_name: mongo-container
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 3
    ports:
      - "27017:27017"
    volumes:
      - mongo-db:/var/lib/mongo
    networks:
      - l_net

  prometheus:
    container_name: prometheus
    image: 'prom/prometheus:v2.14.0'
    ports:
      - '9090:9090'
    command: '--config.file=/etc/prometheus/config.yml'
    volumes:
      - './prometheus.yml:/etc/prometheus/config.yml'
    networks:
      - l_net

  grafana:
    container_name: grafana
    image: 'grafana/grafana:6.5.0'
    restart: "no"
    volumes:
      - /grafana/provisioning/dashboards/local.yml:/conf/provisioning/dashboards/sample.yml
      - /grafana/dashboards/:/var/lib/grafana/dashboards/
    ports:
      - '3000:3000'
    networks:
      - l_net

networks:
  l_net:
    driver: bridge

volumes:
  mysql-db:
  cassandra-db:
  mongo-db:
  minio:
  elasticsearch-db:
  rabbit-log:
  rabbit-conf:
  nodemodules: