spring:
  application:
    name: storage-service
  cloud:
    config:
      uri: http://localhost:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
          jwk-set-uri: http://auth-server:9000/oauth2/jwks
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
minio:
  access-key: myaccesskey
  url: http://localhost:47017
  secret-key: mysecretkey
  bucket: storage