
# ---3---
name: Build and Publish notification-service

on:
  push:
    branches: [ develop ]
    paths:
      - notification-service/**
      - .github/workflows/deploy-notification-service.yaml
jobs:

  maven:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17 Temurin
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin
          cache: 'maven'
          server-id: github
          server-username: USER_NAME
          server-password: ACCESS_TOKEN

      - name: Build with Maven
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: mvn clean install -s ./settings.xml   -pl notification-service

      - name: Temporarily save jar artifact
        uses: actions/upload-artifact@v2
        with:
          name: notification-service
          path: ${{ github.workspace }}/notification-service/target/*.jar
          retention-days: 1

  docker:
    runs-on: self-hosted
    needs: maven

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: notification-service
          path: ${{ github.workspace }}/notification-service/target/

      - name: Docker build
        run: |
          cd notification-service/
          sudo docker build -f Dockerfile . -t ghcr.io/${{ github.actor }}/notification-service:${{github.run_number}}

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Push
        run: sudo docker push ghcr.io/${{ github.actor }}/notification-service:${{github.run_number}}

  run:
    runs-on: self-hosted
    needs: [ maven, docker ]

    steps:
      - name: Configure Kubernetes CLI
        uses: azure/setup-kubectl@v1
        with:
          kubeconfig: ${{ env.KUBECONFIG }}

      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v1
        with:
          manifests: |
            k8s/k8s-notification-service.yaml
          command: apply
          args: -f -

 
