name: Build and Publish audit-service

on:
  push:
    branches: [ develop ]
    paths:
      - audit-service/**
      - .github/workflows/deploy-audit-service.yaml
jobs:

  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17 Temurin
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin
          cache: 'maven'
          server-id: github
          server-username: USER_NAME
          server-password: ACCESS_TOKEN

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.6

      - name: Build with Maven
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: mvn clean install -s ./settings.xml  -pl audit-service

      - name: Temporarily save jar artifact
        uses: actions/upload-artifact@v2
        with:
          name: audit-service
          path: ${{ github.workspace }}/audit-service/target/*.jar
          retention-days: 1

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: audit-service
          path: ${{ github.workspace }}/audit-service/target/

      - name: Docker build
        run: |
          cd audit-service/
          ls
          docker build -f Dockerfile . -t ghcr.io/${{ github.actor }}/audit-service:${{github.run_number}}

      - name: Docker push
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        run: docker push ghcr.io/${{ github.actor }}/audit-service:${{github.run_number}}

  run:
    runs-on: self-hosted
    needs: [ build, deploy ]

    steps:
      - name: Run container
        run: |
          docker run chahirchalouati/audit-service:${{github.run_number}}
 
