name: Deploy Common Module

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Java version
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Set version based on tag
        run: |
          echo "Setting version in pom.xml based on GitHub tag"
          tag_name=$(echo ${GITHUB_REF#refs/tags/})
          sed -i "s/<version>.*<\/version>/<version>$tag_name<\/version>/" common/pom.xml

      - name: Build with Maven
        run: mvn -pl common clean package

      - name: Deploy to GitHub Package Registry
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}