
name: Build and Publish notification-service

on:
  push:
    branches: [ develop ]
    paths:
      - notification-service/**

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17 Temurin
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean install -s ./settings.xml  -pl notification-service
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: chahirchalouati/gramify-ms
          tags: ${{github.run_number}}

 
