on:
  push

name: ci
jobs:
  ci:
    runs-on: self-hosted
    steps:
      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - run: |
          set -x
          
          docker version
          
          docker run --rm hello-world