name: Maven Package

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17 Temurin
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Build common module
        run: mvn clean install -pl common -DskipTests=true

      - name: Deploy to GitHub Package Registry
        uses: actions/upload-artifact@v2
        with:
          name: common
          path: common/target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}