
name: Build and Publish audit-service

on:
  push:
    branches: [ develop ]
    paths:
      - audit-service/**
      - .github/workflows/deploy-audit-service.yaml
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17 Temurin
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin
          cache: 'maven'
          server-id: github
          server-username: USER_NAME
          server-password: ACCESS_TOKEN

      - name: Build with Maven
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: mvn clean install -s ./settings.xml  -pl audit-service

      - name: Temporarily save jar artifact
        uses: actions/upload-artifact@v2
        with:
          name: audit-service
          path: ${{ github.workspace }}/audit-service/target/*.jar
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: audit-service
          path: ${{ github.workspace }}/audit-service/target/

      - name: Docker build
        run: |
          cd audit-service/
          ls
          docker build -f Dockerfile . -t chahirchalouati/audit-service:${{github.run_number}}

      - name: Login to DockerHub
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        uses: docker/login-action@v2
        with:
          username: ${{ env.USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Docker push
        run: |
          docker push chahirchalouati/audit-service:${{github.run_number}}
  run:
    runs-on: ubuntu-latest
    needs: [build, deploy]

    steps:
      - name: Run container
        run: |
          docker run chahirchalouati/audit-service:${{github.run_number}}
 
