
# ---1---
name: Build and Publish comment-service

on:
  push:
    branches: [ develop ]
    paths:
      - comment-service/**
      - .github/workflows/deploy-comment-service.yaml
jobs:

  maven:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17 Temurin
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin
          cache: 'maven'
          server-id: github
          server-username: USER_NAME
          server-password: ACCESS_TOKEN



      - name: Build with Maven
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: mvn clean install -s ./settings.xml   -pl comment-service

      - name: Temporarily save jar artifact
        uses: actions/upload-artifact@v2
        with:
          name: comment-service
          path: ${{ github.workspace }}/comment-service/target/*.jar
          retention-days: 1

  docker:
    runs-on: self-hosted
    needs: maven

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: comment-service
          path: ${{ github.workspace }}/comment-service/target/

      - name: Docker build
        run: |
          cd comment-service/
          docker build -f Dockerfile . -t ghcr.io/${{ github.actor }}/comment-service:${{github.run_number}}

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Push
        run: docker push ghcr.io/${{ github.actor }}/comment-service:${{github.run_number}}

  run:
    runs-on: self-hosted
    needs: [ maven, docker ]

    steps:
      - name: Run container
        run: |
          docker run chahirchalouati/comment-service:${{github.run_number}}

 
