name: Maven Package

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17 Temurin
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin
          cache: 'maven'

      - name: Build common module
        run: mvn clean install -s $GITHUB_WORKSPACE/settings.xml  -pl common -DskipTests=true

      - name: Deploy to GitHub Package Registry
        uses: actions/upload-artifact@v2
        with:
          name: common
          path: common/target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
name: Build and Publish common

on:
  push:
    branches: [ develop ]
    paths:
      - common/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17 Temurin
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean install -s $GITHUB_WORKSPACE/settings.xml  -pl common
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: chahirchalouati/gramify-ms
          tags: ${{github.run_number}}

 
